### ISSUE TITLE
database validation is broken at v2.8.0

### ISSUE THREAD

**Issue by martve** [keeps/dbptk-enterprise#25]
keeps/dbvtk:v2.8.0 database validation at web UI is giving error:
**[JavaScriptException] (TypeError) : Cannot read properties of null (reading 'nf')**

spring.log:
WARN 1 --- [http-nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.UnsupportedClassVersionError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0] with root cause
..
ERROR 1 --- [http-nio-8080-exec-3] Uncaught                                 : [127.0.0.1] Uncaught Exception: (TypeError) : Cannot read properties of null (reading 'xf')
java.lang.Throwable: null
	at Unknown.td(DefaultMethodCallback.java:52)
	at Unknown.Vzb(AbstractRequestCallback.java:67)
	at Unknown.N8b(Request.java:227)
	at Unknown.d9b(RequestBuilder.java:412)
	at Unknown.anonymous(XMLHttpRequest.java:329)
	at Unknown.XYb(Impl.java:299)
	at Unknown.$Yb(Impl.java:351)
	at Unknown.anonymous(Impl.java:78)

**Comment by luis100** [comment]
Java 8 compatibility issue, being fixed at https://github.com/keeps/dbptk-developer/commit/06e8a016716f04bd065a2fc4b3fdbc64120310b6

**Comment by luis100** [comment]
Please try the latest version
